import { useState } from 'react'
import { documentKind, type UiProperties, type UiAnimation } from '../model/document'
import { CustomSelect } from '../ui/CustomSelect'
import { useEditor } from './editor-state'
import { animationFrames, createUiWidget, defaultAnimation, duplicateComponent, layoutChildren } from './ui-design'

export function UiDesignPanel() {
  const editor = useEditor(), element = editor.selectedElement
  const [error, setError] = useState('')
  if (documentKind(editor.document) !== 'ui') return null
  const ui = element?.ui ?? { role: 'container' as const }
  const update = (patch: Partial<UiProperties>) => { if (element) editor.mutateElements(elements => layoutChildren(elements.map(e => e.id === element.id ? { ...e, ui: { ...ui, ...patch } } : patch.label !== undefined && e.parentId === element.id && e.name === 'Label' ? { ...e, text: patch.label, textHtml: undefined } : e), element.id), false, 'UI properties') }
  const a = ui.animation ?? defaultAnimation
  const animate = (patch: Partial<UiAnimation>) => update({ animation: { ...a, ...patch } })
  const play = () => {
    if (!element) return
    const ids = element.type === 'group' ? editor.page.elements.filter(e => e.parentId === element.id).map(e => e.id) : [element.id]
    for (const id of ids) document.querySelector(`[data-element-id="${id}"]`)?.animate(animationFrames(a), { duration: a.duration, delay: a.delay, easing: a.easing, iterations: a.repeat ? 3 : 1 })
  }
  const number = (label: string, value: number, onChange: (n: number) => void, min = 0, max = 10000) => <label className="ui-field"><span>{label}</span><input type="number" min={min} max={max} value={value} onChange={e => onChange(Math.max(min, Math.min(max, Number(e.target.value))))} /></label>
  return <section className="ui-design-panel">
    <div className="ui-insert-grid">{(['button','input','checkbox','card','navigation','badge','container'] as const).map(role => <button key={role} onClick={() => { const added = createUiWidget(role, Math.max(24, editor.page.width / 2 - 100), Math.max(24, editor.page.height / 2 - 24)); editor.mutateElements(e => [...e, ...added], false, `Insert ${role}`); editor.select(added[0].id) }}>{role}</button>)}</div>
    {element && <>
      {element.type === 'group' && <details open><summary>Dimensions</summary>{number('Width',element.width,width => editor.mutateElements(es => es.map(e => e.id === element.id ? {...e,width} : e.parentId === element.id && e.name === 'Surface' ? {...e,width} : e),false,'Resize component'),16,8192)}{number('Height',element.height,height => editor.mutateElements(es => es.map(e => e.id === element.id ? {...e,height} : e.parentId === element.id && e.name === 'Surface' ? {...e,height} : e),false,'Resize component'),16,8192)}<div className="ui-insert-grid">{editor.page.elements.filter(e=>e.parentId===element.id).map(e=><button key={e.id} onClick={()=>editor.select(e.id)}>{e.name}</button>)}</div></details>}
      <details open><summary>UI & accessibility</summary><label className="ui-field"><span>Role</span><CustomSelect value={ui.role} onChange={e => update({ role: e.target.value as UiProperties['role'] })}>{['container','button','input','checkbox','card','navigation','badge'].map(v => <option key={v}>{v}</option>)}</CustomSelect></label><label className="ui-field"><span>Label</span><input value={ui.label ?? ''} onChange={e => update({ label: e.target.value })} /></label><label className="ui-field"><span>Link</span><input placeholder="https://… or #section" value={ui.href ?? ''} onChange={e => update({ href: e.target.value })} /></label></details>
      <label className="ui-field"><span>Container</span><CustomSelect value={element.parentId ?? ''} onChange={e => editor.updateElement(element.id,{parentId:e.target.value || null})}><option value="">Page</option>{editor.page.elements.filter(e => { if(e.type !== 'group' || e.id === element.id)return false; let p=e.parentId;const seen=new Set<string>();while(p && !seen.has(p)){if(p === element.id)return false;seen.add(p);p=editor.page.elements.find(i=>i.id===p)?.parentId ?? null;}return true }).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</CustomSelect></label>
      {element.type === 'group' && <details open><summary>Auto layout</summary><label className="ui-field"><span>Direction</span><CustomSelect value={ui.layout?.direction ?? 'none'} onChange={e => update({ layout: e.target.value === 'none' ? undefined : { direction: e.target.value as 'row' | 'column', gap: 16, padding: 16, align: 'start', justify: 'start' } })}><option value="none">Free layout</option><option value="row">Horizontal</option><option value="column">Vertical</option></CustomSelect></label>{ui.layout && <>{number('Gap', ui.layout.gap, gap => update({ layout: { ...ui.layout!, gap } }))}{number('Padding', ui.layout.padding, padding => update({ layout: { ...ui.layout!, padding } }))}<label className="ui-field"><span>Align</span><CustomSelect value={ui.layout.align} onChange={e => update({ layout: { ...ui.layout!, align: e.target.value as 'start' | 'center' | 'end' } })}>{['start','center','end'].map(v => <option key={v}>{v}</option>)}</CustomSelect></label><label className="ui-field"><span>Distribute</span><CustomSelect value={ui.layout.justify} onChange={e => update({ layout: { ...ui.layout!, justify: e.target.value as NonNullable<UiProperties['layout']>['justify'] } })}>{['start','center','end','space-between'].map(v => <option key={v}>{v}</option>)}</CustomSelect></label><button onClick={() => editor.mutateElements(e => layoutChildren(e, element.id), false, 'Apply layout')}>Apply layout</button></>}</details>}
      <details><summary>Component</summary><label className="ui-field"><span>Name</span><input value={ui.component?.name ?? element.name} onChange={e => update({ component: { ...ui.component, name: e.target.value } })} /></label><button onClick={() => { const copies = duplicateComponent(editor.page.elements, element.id); editor.mutateElements(e => [...e, ...copies], false, 'Create component instance'); editor.select(copies[0].id) }}>Create instance</button>{ui.component?.sourceId && <button onClick={() => { const source = editor.page.elements.find(e => e.id === ui.component?.sourceId); if (!source) return; const copies = duplicateComponent(editor.page.elements, source.id); const root = copies[0]; const oldIds = new Set([element.id]); let changed = true; while (changed) { changed = false; for (const e of editor.page.elements) if (e.parentId && oldIds.has(e.parentId) && !oldIds.has(e.id)) { oldIds.add(e.id); changed = true } } editor.mutateElements(es => [...es.filter(e => !oldIds.has(e.id)), ...copies.map(e => ({ ...e, x: e.x + element.x - root.x, y: e.y + element.y - root.y }))], false, 'Refresh instance'); editor.select(root.id) }}>Update from source</button>}</details>
      <details open><summary>Motion</summary><label className="ui-field"><span>Animation</span><CustomSelect value={ui.animation?.preset ?? 'none'} onChange={e => update({ animation: e.target.value === 'none' ? undefined : { ...a, preset: e.target.value as UiAnimation['preset'] } })}>{['none','fade','rise','scale','custom'].map(v => <option key={v}>{v}</option>)}</CustomSelect></label>{ui.animation && <><label className="ui-field"><span>Trigger</span><CustomSelect value={a.trigger} onChange={e => animate({ trigger: e.target.value as UiAnimation['trigger'] })}>{['load','hover','click'].map(v => <option key={v}>{v}</option>)}</CustomSelect></label>{number('Duration · ms',a.duration,n => animate({ duration: n }), 50,60000)}{number('Delay · ms',a.delay,n => animate({ delay: n }),0,60000)}{number('Distance · px',a.distance,n => animate({ distance: n }),-10000,10000)}<label className="ui-field"><span>Easing</span><CustomSelect value={a.easing} onChange={e => animate({ easing: e.target.value as UiAnimation['easing'] })}>{['linear','ease','ease-in','ease-out','ease-in-out'].map(v => <option key={v}>{v}</option>)}</CustomSelect></label><label className="ui-field"><span>Repeat</span><input type="checkbox" checked={a.repeat} onChange={e => animate({ repeat: e.target.checked })} /></label>{a.preset === 'custom' && <textarea aria-label="Animation keyframes JSON" key={element.id} defaultValue={JSON.stringify(a.keyframes ?? [{offset:0,opacity:0,translateY:24},{offset:1,opacity:1,translateY:0}],null,2)} onBlur={e => { try { const frames = JSON.parse(e.target.value); if (!Array.isArray(frames) || frames.length < 2 || frames.length > 100 || frames.some(f => !Number.isFinite(f.offset) || f.offset < 0 || f.offset > 1 || Object.entries(f).some(([k,v]) => !['offset','opacity','translateX','translateY','scale','rotate'].includes(k) || typeof v !== 'number' || !Number.isFinite(v)))) throw Error(); animate({ keyframes: frames }); setError('') } catch { setError('Use 2–100 numeric keyframes, offsets 0–1.') } }} />}<button onClick={play}>Preview motion</button>{error && <p role="alert">{error}</p>}</>}</details>
    </>}
    <details><summary>Advanced</summary><label className="ui-field"><span>Pixel tools</span><input type="checkbox" checked={editor.drawingMode === 'pixel'} onChange={e => editor.setDrawingMode(e.target.checked ? 'pixel' : 'vector')} /></label></details>
  </section>
}
