export interface Analysis { bpm: number; confidence: number; beatOffset: number; key: string; pitch: number; minor: boolean; energy: number }
// Onset autocorrelation estimates tempo; chroma templates estimate the tonal centre.
export function analyzeAudio(samples: Float32Array, sampleRate: number): Analysis {
  const hop = Math.max(1, Math.round(sampleRate / 100)); const envelope: number[] = []; let previous = 0; let power = 0
  for (let start = 0; start < samples.length; start += hop) { let rms = 0; for (let i = start; i < Math.min(samples.length, start + hop); i++) rms += samples[i] ** 2; rms = Math.sqrt(rms / hop); power += rms * rms; envelope.push(Math.max(0, rms - previous)); previous = rms }
  const mean = envelope.reduce((a, b) => a + b, 0) / Math.max(1, envelope.length); const centred = envelope.map((v) => v - mean); let best = 0; let bestLag = 50; let norm = 0
  for (const v of centred) norm += v * v
  for (let lag = 33; lag <= 100; lag++) { let score = 0; for (let i = lag; i < centred.length; i++) score += centred[i] * centred[i - lag]; score /= Math.max(1e-12, norm); if (score > best) { best = score; bestLag = lag } }
  const chroma = new Array<number>(12).fill(0); const window = 2048; const stride = Math.max(window, Math.floor(samples.length / 80))
  for (let at = 0; at + window < samples.length; at += stride) for (let midi = 48; midi < 84; midi++) { const frequency = 440 * 2 ** ((midi - 69) / 12); if (frequency >= sampleRate / 2) continue; const coefficient = 2 * Math.cos(2 * Math.PI * frequency / sampleRate); let s1 = 0; let s2 = 0; for (let i = 0; i < window; i++) { const s = samples[at + i] * (.5 - .5 * Math.cos(2 * Math.PI * i / (window - 1))) + coefficient * s1 - s2; s2 = s1; s1 = s } chroma[midi % 12] += Math.sqrt(Math.max(0, s1 * s1 + s2 * s2 - coefficient * s1 * s2)) }
  const major = [6.35, 2.23, 3.48, 2.33, 4.38, 4.09, 2.52, 5.19, 2.39, 3.66, 2.29, 2.88]; const minorProfile = [6.33, 2.68, 3.52, 5.38, 2.6, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17]; let pitch = 0; let minor = false; let keyScore = -Infinity; const average = chroma.reduce((a, b) => a + b, 0) / 12
  for (let root = 0; root < 12; root++) for (const [mode, profile] of [major, minorProfile].entries()) { const pmean = profile.reduce((a, b) => a + b, 0) / 12; let dot = 0; let denominator = 0; let pnorm = 0; for (let note = 0; note < 12; note++) { const a = chroma[(note + root) % 12] - average; const b = profile[note] - pmean; dot += a * b; denominator += a * a; pnorm += b * b } const score = dot / Math.sqrt(Math.max(1e-12, denominator * pnorm)); if (score > keyScore) { keyScore = score; pitch = root; minor = mode === 1 } }
  const first = envelope.findIndex((v) => v > mean * 3 && v > .003)
  const names = ['C', 'C♯', 'D', 'E♭', 'E', 'F', 'F♯', 'G', 'A♭', 'A', 'B♭', 'B']; const tonal = chroma.some((v) => v > .001)
  return { bpm: Math.round(6000 / bestLag * 10) / 10, confidence: Math.max(0, Math.min(1, best)), beatOffset: Math.max(0, first) / 100, key: tonal ? `${names[pitch]} ${minor ? 'minor' : 'major'}` : 'Unknown', pitch, minor, energy: Math.min(100, Math.round(Math.sqrt(power / Math.max(1, envelope.length)) * 240)) }
}
export function compatibility(a: { bpm: number; pitch: number; minor: boolean; energy: number; key: string }, b: { bpm: number; pitch: number; minor: boolean; energy: number; key: string }) { const relativeA = (a.pitch + (a.minor ? 3 : 0)) % 12; const relativeB = (b.pitch + (b.minor ? 3 : 0)) % 12; const distance = (relativeB - relativeA + 12) % 12; const harmonic = a.key !== 'Unknown' && b.key !== 'Unknown' && [0, 5, 7].includes(distance); const tempo = Math.abs(a.bpm - b.bpm) / Math.max(a.bpm, b.bpm); return { score: Math.round(Math.max(0, 100 - tempo * 150 - Math.abs(a.energy - b.energy) * .4 - (harmonic ? 0 : 25))), harmonic, tempo } }
