import type { AudioTrack } from '../model/document'
export interface Song extends AudioTrack { notes: string; peaks: number[]; key: string; pitch: number; minor: boolean; energy: number; confidence: number }
export interface Playlist { id: string; name: string; songs: string[]; notes: string }
export interface Library { songs: Song[]; playlists: Playlist[] }
export const emptyLibrary = (): Library => ({ songs: [], playlists: [] })
const database = () => new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open('edon.audio.v1', 2); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains('assets')) request.result.createObjectStore('assets'); if (!request.result.objectStoreNames.contains('library')) request.result.createObjectStore('library') }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) })
async function transaction<T>(store: string, mode: IDBTransactionMode, action: (store: IDBObjectStore) => IDBRequest<T>): Promise<T> { const db = await database(); try { return await new Promise<T>((resolve, reject) => { const tx = db.transaction(store, mode); const request = action(tx.objectStore(store)); tx.oncomplete = () => resolve(request.result); tx.onerror = () => reject(tx.error); tx.onabort = () => reject(tx.error) }) } finally { db.close() } }
export async function saveAudioAsset(id: string, file: Blob): Promise<void> { await transaction('assets', 'readwrite', (store) => store.put(file, id)) }
export async function loadAudioAsset(id: string): Promise<Blob | undefined> { return transaction('assets', 'readonly', (store) => store.get(id)) }
export async function loadLibrary(): Promise<Library> { return (await transaction<Library | undefined>('library', 'readonly', (store) => store.get('main'))) ?? emptyLibrary() }
export async function saveLibrary(library: Library): Promise<void> { await transaction('library', 'readwrite', (store) => store.put(library, 'main')) }
export async function backupLibrary(library: Library): Promise<Blob> { const assets: Blob[] = []; const sizes: number[] = []; for (const song of library.songs) { const blob = await loadAudioAsset(song.assetId); if (!blob) throw new Error(`Missing audio: ${song.name}`); assets.push(blob); sizes.push(blob.size) } const manifest = new TextEncoder().encode(JSON.stringify({ format: 'edon-music-1', library, sizes })); const size = new ArrayBuffer(4); new DataView(size).setUint32(0, manifest.length, true); return new Blob([size, manifest, ...assets], { type: 'application/octet-stream' }) }
export async function restoreLibrary(file: Blob): Promise<Library> { const length = new DataView(await file.slice(0, 4).arrayBuffer()).getUint32(0, true); if (length > 20_000_000 || length + 4 > file.size) throw new Error('Invalid library backup'); const data = JSON.parse(await file.slice(4, 4 + length).text()) as { format: string; library: Library; sizes: number[] }; if (data.format !== 'edon-music-1' || !Array.isArray(data.library?.songs) || !Array.isArray(data.library?.playlists) || data.sizes.length !== data.library.songs.length || data.sizes.some((size) => !Number.isSafeInteger(size) || size < 0) || data.sizes.reduce((sum, size) => sum + size, length + 4) !== file.size) throw new Error('Invalid library backup'); let offset = length + 4; for (const [index, song] of data.library.songs.entries()) { await saveAudioAsset(song.assetId, file.slice(offset, offset + data.sizes[index])); offset += data.sizes[index] } return data.library }
