import { useMemo, useRef, type PointerEvent } from 'react'
import { Pause, Play, Square, X } from 'lucide-react'
import type { AudioTrack } from '../model/document'
import { SignalView } from './SignalView'
import type { Slot, Voice } from './dj-transport'
import { CustomSelect } from '../ui/CustomSelect'
const clock = (time: number) => `${Math.floor(time / 60)}:${String(Math.floor(time % 60)).padStart(2, '0')}`
export function Deck({ slot, track, peaks, position, playing, voice, level, loading, onDrop, onPlay, onStop, onSeek, onPatch, onRemove }: { slot: Slot; track?: AudioTrack; peaks: number[]; position: number; playing: boolean; voice?: Voice; level: number; loading: boolean; onDrop: (id: string) => void; onPlay: () => void; onStop: () => void; onSeek: (time: number) => void; onPatch: (patch: Partial<AudioTrack>) => void; onRemove: () => void }) {
  const name = slot === 0 ? 'A' : 'B'; const scrub = useRef(false)
  const path = useMemo(() => peaks.map((peak, i) => `M${i / peaks.length * 600},${40 - peak * 38}v${peak * 76}`).join(' '), [peaks])
  const seek = (e: PointerEvent<HTMLDivElement>) => { if (!track) return; const rect = e.currentTarget.getBoundingClientRect(); onSeek(Math.max(track.start, Math.min(track.end, (e.clientX - rect.left) / rect.width * track.duration))) }
  return <section className={`dj-deck deck-${name}`} aria-label={`Deck ${name}`} onDragOver={(e) => { if (e.dataTransfer.types.includes('application/edon-song')) e.preventDefault() }} onDrop={(e) => { const id = e.dataTransfer.getData('application/edon-song'); if (id) { e.preventDefault(); onDrop(id) } }}><header><b>{name}</b><div><strong>{track?.name ?? `Drop a song on deck ${name}`}</strong><small>{loading ? 'Loading audio…' : track ? `${track.bpm} BPM · ${clock(track.duration)}` : 'Independent player'}</small></div>{track && <button aria-label={`Unload deck ${name}`} onClick={onRemove}><X size={12} /></button>}</header>
    <div className="dj-wave" role="slider" tabIndex={track ? 0 : -1} aria-label={`${name} waveform playhead`} aria-valuemin={track?.start ?? 0} aria-valuemax={track?.end ?? 0} aria-valuenow={position} onKeyDown={(e) => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); onSeek(position + (e.key === 'ArrowRight' ? 1 : -1)) } }} onPointerDown={(e) => { if (!track) return; scrub.current = true; e.currentTarget.setPointerCapture(e.pointerId); seek(e) }} onPointerMove={(e) => { if (scrub.current) seek(e) }} onPointerUp={(e) => { scrub.current = false; if (e.currentTarget.hasPointerCapture(e.pointerId)) e.currentTarget.releasePointerCapture(e.pointerId) }} onPointerCancel={() => { scrub.current = false }}><svg viewBox="0 0 600 80" preserveAspectRatio="none" aria-hidden="true"><path d={path} stroke="currentColor" strokeWidth="1.3" /><rect x="0" y="0" width={track ? position / track.duration * 600 : 0} height="80" fill="currentColor" opacity=".08" />{track?.cue !== undefined && <path d={`M${track.cue / track.duration * 600},0v80`} stroke="#fff" strokeDasharray="3 3" />}</svg><i className="dj-playhead" style={{ left: `${track ? position / track.duration * 100 : 0}%` }} />{!track && <span>Drag from the library below</span>}</div>
    <div className="dj-deck-transport"><button className="dj-deck-play" aria-label={`${playing ? 'Pause' : 'Play'} deck ${name}`} disabled={!track || loading} onClick={onPlay}>{playing ? <Pause size={14} /> : <Play size={14} />}</button><button aria-label={`Stop deck ${name}`} disabled={!track} onClick={onStop}><Square size={12} /></button><button disabled={!track} onClick={() => { onStop(); onSeek(track?.cue ?? track?.start ?? 0) }}>Cue</button><button disabled={!track} onClick={() => onPatch({ cue: position })}>Set cue</button><output>{clock(position)} / {clock(track?.duration ?? 0)}</output><div className={`dj-level ${level > .98 ? 'clipping' : ''}`} aria-label={`${name} output meter`}><i style={{ width: `${Math.min(100, level * 100)}%` }} /></div></div>
    {track && <><SignalView track={track} voice={voice} /><div className="dj-deck-controls"><Control label={`${name} Low`} value={track.low} min={-24} max={12} unit="dB" onChange={(low) => onPatch({ low })} /><Control label={`${name} Mid`} value={track.mid} min={-24} max={12} unit="dB" onChange={(mid) => onPatch({ mid })} /><Control label={`${name} High`} value={track.high} min={-24} max={12} unit="dB" onChange={(high) => onPatch({ high })} /><Control label={`${name} Filter`} value={track.filter ?? 0} min={-1} max={1} step={.01} unit="" onChange={(filter) => onPatch({ filter })} /><Control label={`${name} Echo`} value={track.echo ?? 0} min={0} max={.7} step={.01} unit="" onChange={(echo) => onPatch({ echo })} /><Control label={`${name} Reverb`} value={track.reverb ?? 0} min={0} max={.7} step={.01} unit="" onChange={(reverb) => onPatch({ reverb })} /></div><div className="dj-deck-secondary"><label>Loop <CustomSelect aria-label={`${name} loop beats`} value={track.loopBeats ?? 0} onChange={(e) => onPatch({ loopBeats: Number(e.target.value) })}>{[0, 4, 8, 16].map((beats) => <option key={beats} value={beats}>{beats ? `${beats} beats` : 'Off'}</option>)}</CustomSelect></label><details><summary>More</summary><div><Control label={`${name} Pan`} value={track.pan ?? 0} min={-1} max={1} step={.01} unit="" onChange={(pan) => onPatch({ pan })} /><Control label={`${name} Resonance`} value={track.resonance ?? .7} min={.1} max={8} step={.1} unit="" onChange={(resonance) => onPatch({ resonance })} /><label>BPM<input aria-label={`${name} track BPM`} type="number" value={track.bpm} min={30} max={300} onChange={(e) => onPatch({ bpm: Math.max(30, Math.min(300, Number(e.target.value) || 120)) })} /></label><label>Trim start<input aria-label={`${name} trim start`} type="number" min={0} max={track.end - .1} step={.1} value={track.start} onChange={(e) => onPatch({ start: Math.min(track.end - .1, Math.max(0, Number(e.target.value))) })} /></label><label>Trim end<input aria-label={`${name} trim end`} type="number" min={track.start + .1} max={track.duration} step={.1} value={track.end} onChange={(e) => onPatch({ end: Math.max(track.start + .1, Math.min(track.duration, Number(e.target.value))) })} /></label></div></details><button onClick={() => onPatch({ low: 0, mid: 0, high: 0, filter: 0, echo: 0, reverb: 0, pan: 0, resonance: .7 })}>Reset FX</button></div></>}
  </section>
}
export function Control({ label, value, min, max, step = .5, unit = '', onChange }: { label: string; value: number; min: number; max: number; step?: number; unit?: string; onChange: (value: number) => void }) { return <label className="dj-control"><span>{label.endsWith('Level') ? label : label.replace(/^[AB] /, '')}<output>{Number(value.toFixed(2))}{unit}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onDoubleClick={() => onChange(Math.max(min, Math.min(max, 0)))} onChange={(e) => onChange(Number(e.target.value))} /></label> }
