import { useRef, useState, type ReactNode } from 'react'
import { GripHorizontal, Maximize2 } from 'lucide-react'
import { FloatingWindow } from '../ui/FloatingWindow'
export type PaneId = 'decks' | 'mixer' | 'library' | 'queue'
const initial: PaneId[] = ['decks', 'mixer', 'library', 'queue']
export function DJDashboard({ panes }: { panes: Record<PaneId, { title: string; content: ReactNode }> }) {
  const [order, setOrder] = useState<PaneId[]>(() => { try { const saved = JSON.parse(localStorage.getItem('edon.dj.layout') ?? 'null'); return Array.isArray(saved) && saved.length === 4 && new Set(saved).size === 4 && saved.every((id) => initial.includes(id)) ? saved : initial } catch { return initial } })
  const [floating, setFloating] = useState<PaneId[]>([])
  const [split, setSplit] = useState(75)
  const drag = useRef<{ id: PaneId; x: number; y: number } | null>(null)
  const grid = useRef<HTMLDivElement>(null)
  const swap = (source: PaneId, target: PaneId) => { const next = [...order]; const a = next.indexOf(source); const b = next.indexOf(target); [next[a], next[b]] = [next[b], next[a]]; setOrder(next); localStorage.setItem('edon.dj.layout', JSON.stringify(next)) }
  return <div ref={grid} className="dj-dashboard" style={{ gridTemplateRows: `minmax(200px, ${split}fr) 7px minmax(130px, ${100 - split}fr)` }}>{order.map((id, index) => { const pane = panes[id]; const floated = floating.includes(id); const body = <div className={`dj-pane-body dj-pane-${id}`}>{pane.content}</div>; return <section key={id} className="dj-pane" data-dj-pane={id} style={{ gridColumn: index % 2 + 1, gridRow: index < 2 ? 1 : 3 }} onDragOver={(e) => { if (e.dataTransfer.types.includes('application/edon-panel')) e.preventDefault() }} onDrop={(e) => { const from = e.dataTransfer.getData('application/edon-panel') as PaneId; if (initial.includes(from)) { e.preventDefault(); e.stopPropagation(); swap(from, id) } }}><header className="dj-pane-heading"><span style={{ touchAction: 'none' }} onPointerDown={(e) => { drag.current = { id, x: e.clientX, y: e.clientY }; e.currentTarget.setPointerCapture(e.pointerId) }} onPointerUp={(e) => { const origin = drag.current; drag.current = null; if (e.currentTarget.hasPointerCapture(e.pointerId)) e.currentTarget.releasePointerCapture(e.pointerId); if (!origin || Math.hypot(e.clientX - origin.x, e.clientY - origin.y) < 6) return; const target = document.elementFromPoint(e.clientX, e.clientY)?.closest('[data-dj-pane]')?.getAttribute('data-dj-pane') as PaneId; if (initial.includes(target) && target !== origin.id) swap(origin.id, target) }} onPointerCancel={() => { drag.current = null }}><GripHorizontal size={13} />{pane.title}</span><button aria-label={`Float ${pane.title}`} onClick={() => setFloating([...floating, id])}><Maximize2 size={12} /></button></header>{floated ? <><button className="dj-redock" onClick={() => setFloating(floating.filter((item) => item !== id))}>Dock {pane.title}</button><FloatingWindow id={`dj-${id}`} title={pane.title} subtitle="Drag header · resize lower right · close to dock" initialPosition={{ x: 40 + index * 25, y: 80 + index * 20 }} onClose={() => setFloating(floating.filter((item) => item !== id))}>{body}</FloatingWindow></> : body}</section> })}<div role="separator" aria-label="Resize dashboard rows" aria-orientation="horizontal" aria-valuemin={30} aria-valuemax={82} aria-valuenow={split} tabIndex={0} className="dj-dashboard-divider" onKeyDown={(e) => { if (e.key === 'ArrowUp' || e.key === 'ArrowDown') { e.preventDefault(); setSplit((value) => Math.max(30, Math.min(82, value + (e.key === 'ArrowDown' ? 2 : -2)))) } }} onPointerDown={(e) => e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={(e) => { if (e.currentTarget.hasPointerCapture(e.pointerId)) { const bounds = grid.current!.getBoundingClientRect(); setSplit(Math.max(30, Math.min(82, (e.clientY - bounds.top) / bounds.height * 100))) } }} onPointerUp={(e) => e.currentTarget.releasePointerCapture(e.pointerId)} /></div>
}
