import { useRef, useState, type PointerEvent } from 'react'
import { createId, type AudioTrack, type FadeParameter, type FadePlan, type FadePreset, type FadeRoute } from '../model/document'
import { CustomSelect } from '../ui/CustomSelect'
import { fadeParameters, fadeProgress, makeFadePlan, routeValue } from './fade-plan'

export function FadePlanner({ plan, presets, crossfade, tracks, onChange, onSave }: { plan: FadePlan; presets: FadePreset[]; crossfade: number; tracks: (AudioTrack | undefined)[]; onChange: (plan: FadePlan) => void; onSave: (presets: FadePreset[]) => void }) {
  const [selected, setSelected] = useState(''); const [editing, setEditing] = useState(false); const [name, setName] = useState('My transition')
  const [parameter, setParameter] = useState<FadeParameter>('filter'); const [deck, setDeck] = useState<0 | 1>(0)
  const drag = useRef<number | null>(null)
  const active = plan.routes.find((route) => route.id === selected) ?? plan.routes[0]
  const progress = fadeProgress(plan, crossfade)
  const changeRoute = (id: string, patch: Partial<FadeRoute>) => onChange({ ...plan, routes: plan.routes.map((route) => route.id === id ? { ...route, ...patch } : route) })
  const movePoint = (event: PointerEvent<SVGSVGElement>) => {
    if (drag.current === null || !active) return
    const rect = event.currentTarget.getBoundingClientRect(); const limits = fadeParameters[active.parameter]
    const points = active.points.map((point, index) => index !== drag.current ? point : { at: Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), value: Math.round(Math.max(limits.min, Math.min(limits.max, limits.max - (event.clientY - rect.top) / rect.height * (limits.max - limits.min))) / limits.step) * limits.step })
    changeRoute(active.id, { points })
  }
  return <section className="dj-fade-planner" aria-label="Fade Planner">
    <header><strong>Fade Planner</strong><button aria-pressed={plan.enabled} onClick={() => onChange({ ...plan, enabled: !plan.enabled })}>{plan.enabled ? 'Plan active' : 'Arm plan'}</button><CustomSelect aria-label="Fade direction" value={plan.from} onChange={(e) => onChange({ ...plan, from: Number(e.target.value) as 0 | 1 })}><option value={0}>A → B</option><option value={1}>B → A</option></CustomSelect><small>{Math.round(progress * 100)}% · follows crossfader</small><button aria-expanded={editing} onClick={() => setEditing(!editing)}>Edit routes</button></header>
    <div className="dj-plan-overview"><div><svg role="img" aria-label="Fade automation curves" viewBox="0 0 400 55" preserveAspectRatio="none"><path d="M0 27.5H400M100 0V55M200 0V55M300 0V55" stroke="#34424f" fill="none" />{plan.routes.map((route) => { const limits = fadeParameters[route.parameter]; return <path key={route.id} className={route.deck === 0 ? 'fade-a' : 'fade-b'} opacity={route.enabled ? 1 : .2} fill="none" strokeWidth={route.id === active?.id ? 2 : 1} d={Array.from({ length: 101 }, (_, i) => `${i ? 'L' : 'M'}${i * 4},${53 - (routeValue(route, i / 100) - limits.min) / (limits.max - limits.min) * 51}`).join(' ')} /> })}<line x1={progress * 400} x2={progress * 400} y1={0} y2={55} stroke="white" /></svg><div className="dj-route-chips">{plan.routes.map((route) => <button key={route.id} aria-pressed={route.id === active?.id} onClick={() => { setSelected(route.id); setEditing(true) }}>{route.deck === 0 ? 'A' : 'B'} {fadeParameters[route.parameter].label} · {Number(routeValue(route, progress).toFixed(2))}{!route.enabled ? ' · manual' : ''}</button>)}{!plan.routes.length && <small>Clean fade · add a route to automate a control.</small>}</div></div>
      <nav aria-label="Transition presets">{(['clean', 'bass', 'filter', 'echo'] as const).map((preset) => <button key={preset} onClick={() => { onChange(makeFadePlan(preset, plan.from)); setSelected('') }}>{preset}</button>)}{presets.map((preset) => <button key={preset.id} title={preset.name} onClick={() => { onChange({ ...structuredClone(preset.plan), enabled: false }); setSelected('') }}>{preset.name}</button>)}</nav>
    </div>
    {editing && <div className="dj-plan-edit"><div className="dj-plan-add"><CustomSelect aria-label="New route deck" value={deck} onChange={(e) => setDeck(Number(e.target.value) as 0 | 1)}><option value={0}>A</option><option value={1}>B</option></CustomSelect><CustomSelect aria-label="New route parameter" value={parameter} onChange={(e) => setParameter(e.target.value as FadeParameter)}>{Object.entries(fadeParameters).map(([id, setting]) => <option key={id} value={id}>{setting.label}</option>)}</CustomSelect><button onClick={() => { const existing = plan.routes.find((route) => route.deck === deck && route.parameter === parameter); if (existing) { setSelected(existing.id); changeRoute(existing.id, { enabled: true }); return } const id = createId('route'); const value = tracks[deck]?.[parameter] ?? (parameter === 'volume' ? .8 : 0); onChange({ ...plan, routes: [...plan.routes, { id, deck, parameter, enabled: true, curve: 'smooth', points: [{ at: 0, value }, { at: 1, value }] }] }); setSelected(id) }}>Add route</button><input aria-label="Preset name" value={name} onChange={(e) => setName(e.target.value)} /><button disabled={!name.trim()} onClick={() => onSave([...presets, { id: createId('fade'), name: name.trim(), plan: structuredClone({ ...plan, enabled: false }) }])}>Save preset</button></div>
      {active && <div className="dj-route-editor"><header><b>{active.deck === 0 ? 'A' : 'B'} {fadeParameters[active.parameter].label}</b><button aria-pressed={active.enabled} onClick={() => changeRoute(active.id, { enabled: !active.enabled })}>{active.enabled ? 'Linked' : 'Manual'}</button><CustomSelect aria-label="Route curve" value={active.curve} onChange={(e) => changeRoute(active.id, { curve: e.target.value as FadeRoute['curve'] })}>{['linear', 'smooth', 'easeIn', 'easeOut'].map((curve) => <option key={curve} value={curve}>{curve}</option>)}</CustomSelect><button onClick={() => onChange({ ...plan, routes: plan.routes.filter((route) => route.id !== active.id) })}>Remove route</button></header>
        <svg className="dj-route-point-graph" role="img" aria-label="Drag automation points" viewBox="0 0 400 65" preserveAspectRatio="none" onPointerMove={movePoint} onPointerUp={(e) => { drag.current = null; if (e.currentTarget.hasPointerCapture(e.pointerId)) e.currentTarget.releasePointerCapture(e.pointerId) }} onPointerCancel={() => { drag.current = null }}><path fill="none" stroke="#a9c8df" d={Array.from({ length: 101 }, (_, i) => { const limits = fadeParameters[active.parameter]; return `${i ? 'L' : 'M'}${i * 400 / 100},${65 - (routeValue(active, i / 100) - limits.min) / (limits.max - limits.min) * 65}` }).join(' ')} />{active.points.map((point, i) => { const limits = fadeParameters[active.parameter]; return <circle key={i} cx={point.at * 400} cy={65 - (point.value - limits.min) / (limits.max - limits.min) * 65} r={5} fill="#d8e6f2" onPointerDown={(e) => { e.preventDefault(); drag.current = i; (e.currentTarget.ownerSVGElement as SVGSVGElement).setPointerCapture(e.pointerId) }} /> })}</svg>
        <div className="dj-plan-points">{active.points.map((point, i) => { const limits = fadeParameters[active.parameter]; return <label key={i}>P{i + 1}<input aria-label={`Point ${i + 1} crossfade percent`} type="number" min={0} max={100} step={1} value={Number((point.at * 100).toFixed(1))} onChange={(e) => changeRoute(active.id, { points: active.points.map((p, index) => index === i ? { ...p, at: Math.max(0, Math.min(1, Number(e.target.value) / 100)) } : p) })} />%<input aria-label={`Point ${i + 1} value`} type="number" min={limits.min} max={limits.max} step={limits.step} value={Number(point.value.toFixed(2))} onChange={(e) => changeRoute(active.id, { points: active.points.map((p, index) => index === i ? { ...p, value: Math.max(limits.min, Math.min(limits.max, Number(e.target.value))) } : p) })} />{limits.unit}<button aria-label={`Remove point ${i + 1}`} disabled={active.points.length <= 2} onClick={() => changeRoute(active.id, { points: active.points.filter((_, index) => index !== i) })}>×</button></label> })}<button onClick={() => changeRoute(active.id, { points: [...active.points, { at: .5, value: routeValue(active, .5) }] })}>+ Point</button></div>
      </div>}
      {presets.length > 0 && <details><summary>Manage saved presets</summary>{presets.map((preset) => <button key={preset.id} onClick={() => onSave(presets.filter((item) => item.id !== preset.id))}>Delete {preset.name}</button>)}</details>}<small>Manual changes release that route. Preset buttons load a preview; Arm plan applies it. Position 0% → 100%, not elapsed time.</small>
    </div>}
  </section>
}
