import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowLeft, Music2, Square, Download, SkipForward } from 'lucide-react'
import { createId, type AudioTrack, type EdonDocument, type MusicSession } from '../model/document'
import { loadAudioAsset, saveAudioAsset, loadLibrary, saveLibrary, emptyLibrary, type Library, type Song } from './audio-assets'
import { compatibility, type Analysis } from './analysis'
import { encodeWav, trackDuration, trackStart, waveform, wireTrack } from './audio-engine'
import { DJTransport, deckTrack, type Slot, type Voice } from './dj-transport'
import { MusicLibrary, SongQueue } from './MusicLibrary'
import { SpotifyLibrary } from './SpotifyLibrary'
import { DJDashboard } from './DJDashboard'
import { Control, Deck } from './Deck'

const emptySession: MusicSession = { tracks: [], bpm: 120, sync: false, crossfade: -1 }
interface View { positions: number[]; playing: boolean[]; levels: number[]; crossfade: number; fade: number; fading: boolean; active: Slot; voices: (Voice | undefined)[] }
const emptyView: View = { positions: [0, 0], playing: [false, false], levels: [0, 0], crossfade: -1, fade: 0, fading: false, active: 0, voices: [undefined, undefined] }
const letters = ['A', 'B']
export function MusicEditor({ document: file, onChange, onBack }: { document: EdonDocument; onChange: (document: EdonDocument) => void; onBack: () => void }) {
  const session = file.music ?? emptySession
  const [library, setLibrary] = useState<Library>(emptyLibrary)
  const [view, setView] = useState(emptyView)
  const [peaks, setPeaks] = useState<number[][]>([[], []])
  const [loading, setLoading] = useState([false, false])
  const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(''); const [error, setError] = useState('')
  const [autoMessage, setAutoMessage] = useState('Manual control · A / B: play or pause each deck')
  const [spotifyOpen, setSpotifyOpen] = useState(false)
  const engine = useRef<DJTransport | null>(null)
  const latest = useRef({ file, session, library, onChange }); useEffect(() => { latest.current = { file, session, library, onChange } }, [file, session, library, onChange])
  const alive = useRef(true)
  const requests = useRef([0, 0]); const importBusy = useRef(false)
  const automation = useRef({ active: 0 as Slot, token: 0, preparing: false, advancing: false })
  const pauseSpotify = useRef<() => Promise<void>>(async () => {})
  const registerPause = useCallback((pause: () => Promise<void>) => { pauseSpotify.current = pause }, [])
  const ensureEngine = () => engine.current ??= new DJTransport(new AudioContext())
  const commit = (patch: Partial<MusicSession>) => { const state = latest.current; const music = { ...state.session, ...patch }; const next = { ...state.file, music, revision: state.file.revision + 1, updatedAt: new Date().toISOString() }; latest.current = { ...state, file: next, session: music }; state.onChange(next) }
  const persistLibrary = (next: Library) => { latest.current.library = next; setLibrary(next); void saveLibrary(next).catch((reason: Error) => setError(`Library save failed: ${reason.message}`)) }
  const stopAuto = () => { automation.current.token++; automation.current.preparing = false; automation.current.advancing = false; engine.current?.cancelTransition(); if (latest.current.session.auto) commit({ auto: false, crossfade: engine.current?.crossfade ?? latest.current.session.crossfade }); setAutoMessage('Manual control · automation stopped') }
  const putTrack = (track: AudioTrack, slot: Slot) => { const tracks = latest.current.session.tracks.map((item, index) => ({ ...item, deck: (item.deck ?? index) as Slot })).filter((item) => item.deck !== slot); commit({ tracks: [...tracks, { ...track, deck: slot }].sort((a, b) => a.deck - b.deck) }) }
  const prepareDeck = async (track: AudioTrack, slot: Slot, guard?: number) => {
    const request = ++requests.current[slot]; setLoading((current) => current.map((value, index) => index === slot ? true : value))
    try { const blob = await loadAudioAsset(track.assetId); if (!blob) throw new Error(`Audio missing: ${track.name}. Restore a library backup.`); const player = ensureEngine(); const buffer = await player.context.decodeAudioData(await blob.arrayBuffer()); if (request !== requests.current[slot] || (guard !== undefined && guard !== automation.current.token)) return false; player.load(slot, track, buffer); player.mix(player.crossfade, latest.current.session); const saved = latest.current.library.songs.find((s) => s.assetId === track.assetId); setPeaks((current) => current.map((value, index) => index === slot ? saved?.peaks.length ? saved.peaks : waveform(buffer) : value)); return true } finally { if (request === requests.current[slot]) setLoading((current) => current.map((value, index) => index === slot ? false : value)) }
  }
  const loadDeck = async (song: Song, slot: Slot) => { stopAuto(); engine.current?.pause(slot); const track = { ...song, id: createId('track'), deck: slot }; try { if (await prepareDeck(track, slot)) putTrack(track, slot) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load deck') } }
  useEffect(() => { let cancelled = false; if (session.auto) commit({ auto: false }); void loadLibrary().then(async (saved) => { const legacy: Song[] = session.tracks.filter((track) => !saved.songs.some((s) => s.assetId === track.assetId)).map((track) => ({ ...track, notes: '', peaks: [], key: 'Unknown', pitch: 0, minor: false, energy: 0, confidence: 0 })); const next = { ...saved, songs: [...saved.songs, ...legacy] }; if (!cancelled) { latest.current.library = next; setLibrary(next) } if (legacy.length) await saveLibrary(next) }).catch((reason: Error) => { if (!cancelled) setError(reason.message) }); return () => { cancelled = true }
  // Shared binary library loads once, independently of live mixer parameters.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  useEffect(() => {
    for (const slot of [0, 1] as const) { const track = deckTrack(session, slot); const channel = engine.current?.channels[slot]; if (!track) { if (channel?.track) { engine.current!.pause(slot); engine.current!.channels[slot].track = undefined; engine.current!.channels[slot].buffer = undefined; setPeaks((current) => current.map((p, index) => index === slot ? [] : p)) } } else if (!channel || channel.track?.id !== track.id) { void prepareDeck(track, slot).catch((reason: Error) => setError(reason.message)) } else engine.current!.apply(slot, track, session) }
    if (engine.current && !engine.current.transition) engine.current.mix(session.crossfade, session)
  // Track identity and settings determine when a deck loads or its DSP updates.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [session.tracks, session.bpm, session.sync, session.crossfade])
  const importMany = async (files: File[]) => {
    if (importBusy.current) return; importBusy.current = true; setBusy(true); setError(''); let failed = 0
    try { for (const [index, audio] of files.entries()) { if (!alive.current) break; setProgress(`Scanning ${index + 1}/${files.length}: ${audio.name}`); try { const buffer = await ensureEngine().context.decodeAudioData(await audio.arrayBuffer()); if (!alive.current) break; const stride = Math.max(1, Math.floor(buffer.sampleRate / 8000)); const samples = new Float32Array(Math.ceil(buffer.length / stride)); const channel = buffer.getChannelData(0); for (let i = 0; i < samples.length; i++) samples[i] = channel[i * stride] ?? 0; const analysis = await new Promise<Analysis>((resolve, reject) => { const worker = new Worker(new URL('./analysis.worker.ts', import.meta.url), { type: 'module' }); const timer = setTimeout(() => { worker.terminate(); reject(new Error('Analysis timed out')) }, 120000); worker.onmessage = (event: MessageEvent<Analysis>) => { clearTimeout(timer); worker.terminate(); resolve(event.data) }; worker.onerror = () => { clearTimeout(timer); worker.terminate(); reject(new Error('Audio analysis failed')) }; worker.postMessage({ samples, sampleRate: buffer.sampleRate / stride }, [samples.buffer]) }); if (!alive.current) break; const assetId = createId('audio'); await saveAudioAsset(assetId, audio); const song: Song = { id: createId('track'), assetId, name: audio.name.replace(/\.[^.]+$/, ''), duration: buffer.duration, ...analysis, start: 0, end: buffer.duration, volume: .8, low: 0, mid: 0, high: 0, notes: '', peaks: waveform(buffer) }; const next = { ...latest.current.library, songs: [...latest.current.library.songs, song] }; await saveLibrary(next); latest.current.library = next; setLibrary(next) } catch (reason) { failed++; setError(`${audio.name}: ${reason instanceof Error ? reason.message : 'Import failed'}`) } } } finally { if (alive.current) { setProgress(`${files.length - failed} songs imported${failed ? ` · ${failed} failed` : ''}`); setBusy(false) } importBusy.current = false; void navigator.storage?.persist?.() }
  }
  const patchDeck = (slot: Slot, patch: Partial<AudioTrack>) => { const track = deckTrack(latest.current.session, slot); if (!track) return; const next = { ...track, ...patch }; const tracks = latest.current.session.tracks.map((item) => item.id === track.id ? next : item); commit({ tracks }); engine.current?.apply(slot, next, latest.current.session) }
  const toggleDeck = async (slot: Slot) => { stopAuto(); const player = ensureEngine(); const channel = player.channels[slot]; if (channel.playing) player.pause(slot); else { try { await pauseSpotify.current(); setSpotifyOpen(false); await player.context.resume(); player.play(slot, latest.current.session) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Playback failed') } } }
  const nextSong = () => latest.current.library.songs.find((song) => song.assetId === latest.current.session.queue?.[0])
  const prepareNext = async () => {
    const state = automation.current; const player = engine.current; const song = nextSong(); if (!player || !song || state.preparing || state.advancing || player.transition) return
    const slot = (1 - state.active) as Slot; if (player.channels[slot].playing || player.channels[slot].track?.assetId === song.assetId) return
    state.preparing = true; const token = state.token
    try { const track = { ...song, id: createId('track'), deck: slot, loopBeats: 0 }; if (await prepareDeck(track, slot, token)) { putTrack(track, slot); setAutoMessage(`Prepared ${letters[slot]} · ${song.name}`) } } catch (reason) { stopAuto(); setError(reason instanceof Error ? reason.message : 'Queue preparation failed') } finally { if (token === state.token) state.preparing = false }
  }
  const plan = () => { const player = engine.current; const song = nextSong(); const outgoing = player?.channels[automation.current.active].track; const current = latest.current.library.songs.find((s) => s.assetId === outgoing?.assetId); const match = current && song ? compatibility(current, song) : undefined; let seconds = latest.current.session.transition ?? 8; if (match && (match.tempo > .08 || !match.harmonic)) seconds = Math.min(4, seconds); if (song) seconds = Math.min(seconds, trackDuration(song, latest.current.session) / 2); return { seconds: Math.max(.2, seconds), bass: Boolean(current && song && current.energy > 55 && song.energy > 55), match } }
  const advance = async () => {
    const state = automation.current; const song = nextSong(); const player = engine.current; if (!player || !song || state.advancing || player.transition) return
    state.advancing = true; const token = state.token; const from = state.active; const to = (1 - from) as Slot
    try { if (player.channels[to].track?.assetId !== song.assetId || !player.channels[to].buffer) { const track = { ...song, id: createId('track'), deck: to, loopBeats: 0 }; if (!(await prepareDeck(track, to, token))) return; putTrack(track, to) } if (token !== state.token) return
      await pauseSpotify.current(); await player.context.resume(); if (token !== state.token) return; const settings = latest.current.session; const incoming = player.channels[to]; if (incoming.track) incoming.position = trackStart(incoming.track, settings); const outgoing = player.channels[from]; const beat = outgoing.track ? 60 / outgoing.track.bpm : .5; const phase = outgoing.track ? ((player.position(from) - outgoing.track.beatOffset) % beat + beat) % beat : 0; const wait = settings.sync && outgoing.playing ? Math.max(.025, Math.min(.6, (beat - phase) / outgoing.rate)) : .025; const when = player.context.currentTime + wait; player.play(to, settings, when); const remaining = player.channels[from].track ? (player.channels[from].track!.end - player.position(from)) / player.channels[from].rate : 0; const transitionPlan = plan(); const seconds = Math.max(.2, Math.min(transitionPlan.seconds, remaining > 0 ? Math.max(.2, remaining - wait) : transitionPlan.seconds)); player.beginTransition(from, to, seconds, transitionPlan.bass, when); commit({ queue: (settings.queue ?? []).slice(1) }); setAutoMessage(`${letters[from]} → ${letters[to]} · ${seconds.toFixed(1)} s ${transitionPlan.bass ? '· bass swap' : '· smooth fade'}`)
    } catch (reason) { stopAuto(); setError(reason instanceof Error ? reason.message : 'Transition failed') } finally { if (state.token === token) state.advancing = false }
  }
  const startAuto = async () => {
    const player = ensureEngine(); stopAuto(); automation.current.token++; const token = automation.current.token
    const playing = player.channels.map((channel) => channel.playing); const active: Slot = playing[1] && (!playing[0] || player.crossfade > 0) ? 1 : 0
    automation.current.active = active
    try { await pauseSpotify.current(); setSpotifyOpen(false); await player.context.resume(); if (token !== automation.current.token) return
      if (!player.channels[active].track) { const song = nextSong(); if (!song) throw new Error('Load a deck or add a song to the queue first.'); const track = { ...song, id: createId('track'), deck: active, loopBeats: 0 }; if (!(await prepareDeck(track, active, token))) return; putTrack(track, active); commit({ queue: (latest.current.session.queue ?? []).slice(1) }) }
      if (!player.channels[active].buffer) throw new Error('Wait for the deck to finish loading.'); player.pause((1 - active) as Slot); player.mix(active === 0 ? -1 : 1, latest.current.session); commit({ auto: true, crossfade: player.crossfade }); player.play(active, latest.current.session); setAutoMessage(`Auto DJ · ${letters[active]} playing, next song prepares on ${letters[1 - active]}`); void prepareNext()
    } catch (reason) { stopAuto(); setError(reason instanceof Error ? reason.message : 'Auto DJ failed') }
  }
  useEffect(() => {
    alive.current = true
    const controller = automation.current
    const timer = window.setInterval(() => {
      const player = engine.current; if (!player) return; const state = latest.current; const transition = player.transition
      if (player.tick(state.session) && transition) { automation.current.active = transition.to; commit({ crossfade: player.crossfade }); setAutoMessage(`Auto DJ · ${letters[transition.to]} now playing`); void prepareNext() }
      const levels = player.channels.map((channel) => { if (!channel.voice) return 0; const data = new Float32Array(channel.voice.analyser.fftSize); channel.voice.analyser.getFloatTimeDomainData(data); let sum = 0; for (const value of data) sum += value * value; return Math.sqrt(sum / data.length) * 2.5 })
      setView({ positions: [player.position(0), player.position(1)], playing: player.channels.map((channel) => channel.playing), levels, voices: player.channels.map((channel) => channel.voice), active: state.session.auto ? automation.current.active : player.crossfade > 0 ? 1 : 0, fading: Boolean(player.transition), crossfade: player.crossfade, fade: player.transition ? Math.max(0, Math.min(1, (player.context.currentTime - player.transition.started) / player.transition.duration)) : 0 })
      if (state.session.auto && !player.transition && !automation.current.advancing) { const active = automation.current.active; const channel = player.channels[active]; if (nextSong()) { void prepareNext(); if (channel.track && !channel.track.loopBeats && (channel.track.end - player.position(active)) / channel.rate <= plan().seconds) void advance() } else if (!channel.playing && channel.track) { commit({ auto: false }); setAutoMessage('Queue finished') } }
    }, 60)
    return () => { clearInterval(timer); alive.current = false; controller.token++; requests.current = requests.current.map((request) => request + 1); engine.current?.close(); engine.current = null }
  // One audio-clock loop reads current state through refs; EQ edits must not restart it.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  const setCrossfade = (crossfade: number) => { stopAuto(); ensureEngine().mix(crossfade, latest.current.session); commit({ crossfade }); setView((current) => ({ ...current, crossfade })) }
  const stopAll = () => { stopAuto(); engine.current?.stop() }
  const exportMix = async () => { setBusy(true); setError(''); try { const state = latest.current.session; const duration = Math.max(0, ...state.tracks.map((track) => trackDuration(track, state))); if (!duration || duration > 1800) throw new Error('Deck export supports up to 30 minutes.'); const offline = new OfflineAudioContext(2, Math.ceil(duration * 44100), 44100); state.tracks.forEach((track, index) => { const slot = (track.deck ?? index) as Slot; const buffer = engine.current?.channels[slot].buffer; if (!buffer) throw new Error('Wait for both decks to load'); const voice = wireTrack(offline, buffer, track, state, slot); voice.source.start(0, trackStart(track, state), track.end - trackStart(track, state)) }); const url = URL.createObjectURL(encodeWav(await offline.startRendering())); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${latest.current.file.name}.wav`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 10000) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Export failed') } finally { setBusy(false) } }
  const currentId = deckTrack(session, view.active)?.assetId
  const next = library.songs.find((song) => song.assetId === session.queue?.[0]); const currentSong = library.songs.find((song) => song.assetId === currentId); const match = currentSong && next ? compatibility(currentSong, next) : undefined
  const decks = <div className="dj-decks">{([0, 1] as const).map((slot) => <Deck key={slot} slot={slot} track={deckTrack(session, slot)} peaks={peaks[slot]} position={view.positions[slot]} playing={view.playing[slot]} voice={view.voices[slot]} level={view.levels[slot]} loading={loading[slot]} onDrop={(id) => { const song = library.songs.find((item) => item.assetId === id); if (song) void loadDeck(song, slot) }} onPlay={() => void toggleDeck(slot)} onStop={() => { stopAuto(); engine.current?.pause(slot); const track = deckTrack(latest.current.session, slot); if (engine.current) engine.current.channels[slot].position = track?.start ?? 0 }} onSeek={(time) => { stopAuto(); ensureEngine().seek(slot, time, latest.current.session) }} onPatch={(patch) => patchDeck(slot, patch)} onRemove={() => { stopAuto(); requests.current[slot]++; engine.current?.pause(slot); commit({ tracks: latest.current.session.tracks.filter((track, index) => (track.deck ?? index) !== slot).map((track) => ({ ...track, deck: (1 - slot) as Slot })) }) }} />)}</div>
  const mixer = <div className="dj-mixer"><div className="dj-channel-levels">{([0, 1] as const).map((slot) => <Control key={slot} label={`${letters[slot]} Level`} value={deckTrack(session, slot)?.volume ?? .8} min={0} max={1} step={.01} onChange={(volume) => patchDeck(slot, { volume })} />)}</div><div className="dj-crossfade"><header><strong>A ↔ B</strong><output>{Math.round((view.crossfade + 1) / 2 * 100)}% B</output></header><input aria-label="Crossfader" type="range" min={-1} max={1} step={.01} value={view.crossfade} onChange={(e) => setCrossfade(Number(e.target.value))} /><div className="dj-fade-graph"><svg viewBox="0 0 200 54" preserveAspectRatio="none" aria-label="Equal-power crossfade curves"><path d={Array.from({ length: 101 }, (_, i) => `${i ? 'L' : 'M'}${i * 2},${50 - Math.cos(i / 100 * Math.PI / 2) * 46}`).join(' ')} className="fade-a" /><path d={Array.from({ length: 101 }, (_, i) => `${i ? 'L' : 'M'}${i * 2},${50 - Math.sin(i / 100 * Math.PI / 2) * 46}`).join(' ')} className="fade-b" /><line x1={(view.crossfade + 1) * 100} x2={(view.crossfade + 1) * 100} y1="0" y2="54" stroke="white" /></svg><span>A {Math.round(Math.cos((view.crossfade + 1) * Math.PI / 4) * 100)}% <i>B {Math.round(Math.sin((view.crossfade + 1) * Math.PI / 4) * 100)}%</i></span></div></div><div className="dj-master"><label>Master BPM<input aria-label="Master BPM" type="number" min={30} max={300} value={session.bpm} onChange={(e) => commit({ bpm: Math.max(30, Math.min(300, Number(e.target.value) || 120)) })} /></label><button aria-pressed={session.sync} onClick={() => commit({ sync: !session.sync })}>Sync {session.sync ? 'On' : 'Off'}</button></div><div className="dj-auto"><button className={session.auto ? 'on' : ''} aria-pressed={session.auto ?? false} onClick={() => session.auto ? stopAuto() : void startAuto()}>Auto DJ {session.auto ? 'On' : 'Off'}</button><button aria-label="Transition now" disabled={!session.queue?.length || loading.some(Boolean)} onClick={() => { if (!session.auto) { commit({ auto: true }); automation.current.active = view.crossfade > 0 ? 1 : 0 } void advance() }}><SkipForward size={13} /> Fade now</button><label>Fade time<input aria-label="Transition seconds" type="number" min={1} max={30} value={session.transition ?? 8} onChange={(e) => commit({ transition: Math.max(1, Math.min(30, Number(e.target.value) || 8)) })} />s</label></div><p className="dj-auto-status" role="status">{autoMessage}</p>{view.fading && <progress aria-label="Transition progress" max={1} value={view.fade} />}<small>Sync changes speed and pitch. Move the crossfader to take manual control.</small><details className="dj-spotify"><summary>Spotify player</summary><SpotifyLibrary documentId={file.id} playing={view.playing.some(Boolean)} embedOpen={spotifyOpen} registerPause={registerPause} onPreview={() => { stopAll(); setSpotifyOpen(true) }} /></details></div>
  const queue = <><div className="dj-helper-compact"><strong>DJ helper</strong><p>{match && next ? `${next.name} · ${match.score}% match. ${match.harmonic ? 'Related keys.' : 'Different keys: shorter fade.'} ${match.tempo > .08 ? 'Large tempo change.' : 'Similar tempo.'}` : 'Add songs to the queue to prepare your next transition.'}</p><button disabled={!match} onClick={() => { const pool = (session.queue ?? []).map((id) => library.songs.find((s) => s.assetId === id)).filter((s): s is Song => Boolean(s)); let previous = currentSong; const ordered: string[] = []; while (pool.length) { if (previous) { const reference = previous; pool.sort((a, b) => compatibility(reference, b).score - compatibility(reference, a).score) } previous = pool.shift()!; ordered.push(previous.assetId) } commit({ queue: ordered }) }}>Order by compatibility</button></div><SongQueue library={library} queue={session.queue ?? []} onQueue={(ids) => commit({ queue: ids })} onImport={(files) => void importMany(files)} /></>
  return <main className="music-editor dj-editor" tabIndex={-1} onKeyDown={(e) => { if (['INPUT', 'TEXTAREA', 'BUTTON'].includes((e.target as HTMLElement).tagName) || e.ctrlKey || e.metaKey || e.altKey) return; if (e.key.toLowerCase() === 'a' || e.key.toLowerCase() === 'b') { e.preventDefault(); void toggleDeck(e.key.toLowerCase() === 'a' ? 0 : 1) } if (e.code === 'Space') { e.preventDefault(); const slot = view.crossfade > 0 ? 1 : 0; void toggleDeck(slot) } }}><header className="music-topbar"><button aria-label="Back to files" onClick={() => { stopAll(); onBack() }}><ArrowLeft size={15} /></button><Music2 size={17} /><strong>edon <span>DJ studio</span></strong><input aria-label="Document name" defaultValue={file.name} onBlur={(e) => { if (e.target.value.trim()) latest.current.onChange({ ...latest.current.file, name: e.target.value.trim() }) }} /><small>{progress || 'Drag panel headers to swap · Float panels to move freely'}</small><button onClick={stopAll}><Square size={12} /> Stop all</button><button disabled={busy || !session.tracks.length} onClick={() => void exportMix()} title="Exports loaded decks at the current mixer settings"><Download size={13} /> Export decks</button></header>{error && <div className="dj-error" role="alert">{error}<button onClick={() => setError('')}>Dismiss</button></div>}<DJDashboard panes={{ decks: { title: 'Decks', content: decks }, mixer: { title: 'Mixer & Auto DJ', content: mixer }, library: { title: 'Library & playlists', content: <MusicLibrary library={library} queue={session.queue ?? []} current={currentId} busy={busy} onSave={persistLibrary} onImport={(files) => void importMany(files)} onQueue={(ids) => commit({ queue: ids })} onDeck={(song, slot) => void loadDeck(song, slot as Slot)} /> }, queue: { title: 'Queue & helper', content: queue } }} /></main>
}
