import { useEffect, useRef, useState } from 'react'
import { Plus, Music2, Download, Upload, ListMusic, ArrowUp, ArrowDown, X } from 'lucide-react'
import { createId } from '../model/document'
import { backupLibrary, restoreLibrary, type Library, type Song } from './audio-assets'
import { compatibility } from './analysis'
import { CustomSelect as BaseSelect } from '../ui/CustomSelect'
function CustomSelect({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <BaseSelect value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</BaseSelect> }
export function MusicLibrary({ library, queue, current, busy, onSave, onImport, onQueue, onDeck }: { library: Library; queue: string[]; current?: string; busy: boolean; onSave: (library: Library) => void; onImport: (files: File[]) => void; onQueue: (ids: string[]) => void; onDeck: (song: Song, slot: number) => void }) {
  const [playlist, setPlaylist] = useState('all'); const [query, setQuery] = useState(''); const [sort, setSort] = useState('name'); const [selected, setSelected] = useState<string>(); const [message, setMessage] = useState(''); const [backupUrl, setBackupUrl] = useState(''); useEffect(() => () => { if (backupUrl) URL.revokeObjectURL(backupUrl) }, [backupUrl]); const input = useRef<HTMLInputElement>(null); const restore = useRef<HTMLInputElement>(null)
  const active = library.playlists.find((p) => p.id === playlist); const song = library.songs.find((s) => s.assetId === selected); const playingSong = library.songs.find((s) => s.assetId === current)
  const songs = library.songs.filter((s) => (!active || active.songs.includes(s.assetId)) && s.name.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'bpm' ? a.bpm - b.bpm : sort === 'energy' ? a.energy - b.energy : sort === 'match' && playingSong ? compatibility(playingSong, b).score - compatibility(playingSong, a).score : sort === 'key' ? a.key.localeCompare(b.key) : a.name.localeCompare(b.name))
  const move = (index: number, offset: number) => { const next = [...queue]; const to = index + offset; if (to < 0 || to >= next.length) return; [next[index], next[to]] = [next[to], next[index]]; onQueue(next) }
  const addPlaylist = () => { const id = createId('playlist'); onSave({ ...library, playlists: [...library.playlists, { id, name: `Playlist ${library.playlists.length + 1}`, songs: [], notes: '' }] }); setPlaylist(id) }
  const saveSong = (patch: Partial<Song>) => song && onSave({ ...library, songs: library.songs.map((s) => s.assetId === song.assetId ? { ...s, ...patch } : s) })
  return <section className="dj-library" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); if (e.dataTransfer.files.length) onImport(Array.from(e.dataTransfer.files)) }}>
    <header className="dj-library-header"><div><Music2 size={19} /><strong>Library</strong><small>{library.songs.length} songs · saved in this browser</small></div><button disabled={busy} onClick={() => input.current?.click()}><Plus size={15} /> {busy ? 'Scanning…' : 'Import audio'}</button><button disabled={busy} onClick={() => { setMessage('Creating backup…'); void backupLibrary(library).then((blob) => { const url = URL.createObjectURL(blob); setBackupUrl(url); setMessage('Backup ready with audio, playlists and notes.') }).catch((error: Error) => setMessage(error.message)) }}><Download size={15} /> Backup</button><button disabled={busy} onClick={() => restore.current?.click()}><Upload size={15} /> Restore</button></header>
    <input ref={input} type="file" hidden multiple accept="audio/*,.wav,.flac" onChange={(e) => { onImport(Array.from(e.target.files ?? [])); e.target.value = '' }} /><input ref={restore} hidden type="file" accept=".edonmusic" onChange={(e) => { const file = e.target.files?.[0]; if (file) void restoreLibrary(file).then((incoming) => { onSave({ songs: [...library.songs.filter((s) => !incoming.songs.some((i) => i.assetId === s.assetId)), ...incoming.songs], playlists: [...library.playlists.filter((p) => !incoming.playlists.some((i) => i.id === p.id)), ...incoming.playlists] }); setMessage('Library restored.') }).catch((error: Error) => setMessage(error.message)); e.target.value = '' }} />
    {message && <p role="status">{message} {backupUrl && <a className="backup-download" href={backupUrl} download="Edon-library.edonmusic">Download library backup</a>}</p>}<div className="dj-browser"><nav><button className={playlist === 'all' ? 'active' : ''} onClick={() => setPlaylist('all')}>All songs <span>{library.songs.length}</span></button><h4>Playlists <button aria-label="New playlist" onClick={addPlaylist}><Plus size={14} /></button></h4>{library.playlists.map((p) => <button key={p.id} className={playlist === p.id ? 'active' : ''} onClick={() => setPlaylist(p.id)} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); e.stopPropagation(); const id = e.dataTransfer.getData('application/edon-song'); if (library.songs.some((s) => s.assetId === id)) onSave({ ...library, playlists: library.playlists.map((item) => item.id === p.id ? { ...item, songs: [...new Set([...item.songs, id])] } : item) }) }}><ListMusic size={14} />{p.name}<span>{p.songs.length}</span></button>)}</nav>
    <div className="dj-song-list">{active && <div className="playlist-details"><input aria-label="Playlist name" value={active.name} onChange={(e) => onSave({ ...library, playlists: library.playlists.map((p) => p.id === active.id ? { ...p, name: e.target.value } : p) })} /><textarea aria-label="Playlist notes" placeholder="Playlist notes, atmosphere, transition ideas…" value={active.notes} onChange={(e) => onSave({ ...library, playlists: library.playlists.map((p) => p.id === active.id ? { ...p, notes: e.target.value } : p) })} /><button onClick={() => onQueue([...queue, ...active.songs])}>Add playlist to queue</button><button onClick={() => { onSave({ ...library, playlists: library.playlists.filter((p) => p.id !== active.id) }); setPlaylist('all') }}>Delete playlist</button></div>}
    <div className="dj-search"><input aria-label="Search library" placeholder="Search your songs…" value={query} onChange={(e) => setQuery(e.target.value)} /><CustomSelect value={sort} onChange={setSort} options={[{ value: 'name', label: 'Name' }, { value: 'bpm', label: 'BPM' }, { value: 'key', label: 'Key' }, { value: 'energy', label: 'Energy' }, { value: 'match', label: 'Best match' }]} /></div>
    <div className="dj-column-labels"><span>Song</span><span>BPM</span><span>Key</span><span>Energy</span><span>Actions</span></div>{songs.map((s) => <div key={s.assetId} className={`dj-song ${selected === s.assetId ? 'selected' : ''}`} draggable onDragStart={(e) => e.dataTransfer.setData('application/edon-song', s.assetId)} onClick={() => setSelected(s.assetId)}><strong title={s.name}>{s.name}</strong><span title={`Tempo confidence ${Math.round(s.confidence * 100)}%`}>{s.bpm}</span><span>{s.key}</span><span className="energy-meter"><i style={{ width: `${s.energy}%` }} />{s.energy}</span><div><button aria-label={`Load ${s.name} in A`} onClick={() => onDeck(s, 0)}>A</button><button aria-label={`Load ${s.name} in B`} onClick={() => onDeck(s, 1)}>B</button><button aria-label={`Queue ${s.name}`} onClick={() => onQueue([...queue, s.assetId])}><Plus size={14} /></button>{active && <button aria-label="Remove from playlist" onClick={() => onSave({ ...library, playlists: library.playlists.map((p) => p.id === active.id ? { ...p, songs: p.songs.filter((id) => id !== s.assetId) } : p) })}><X size={13} /></button>}</div></div>)}{!songs.length && <div className="dj-drop"><Upload size={28} /><strong>Drop your audio files here</strong><p>Import once. Use them in any music project.</p></div>}
    {song && <div className="dj-song-notes"><strong>{song.name}</strong>{active && !active.songs.includes(song.assetId) && <button onClick={() => onSave({ ...library, playlists: library.playlists.map((p) => p.id === active.id ? { ...p, songs: [...p.songs, song.assetId] } : p) })}>Add selected song to playlist</button>}<label>Notes<textarea aria-label="Song notes" value={song.notes} placeholder="Cue points, birthday requests, transition ideas…" onChange={(e) => saveSong({ notes: e.target.value })} /></label><div><label>BPM <input type="number" min={30} max={300} value={song.bpm} onChange={(e) => saveSong({ bpm: Math.max(30, Math.min(300, Number(e.target.value) || 120)) })} /></label><label>Key <CustomSelect value={`${song.pitch}:${song.minor ? 1 : 0}`} options={['C', 'C♯', 'D', 'E♭', 'E', 'F', 'F♯', 'G', 'A♭', 'A', 'B♭', 'B'].flatMap((name, pitch) => [false, true].map((minor) => ({ value: `${pitch}:${minor ? 1 : 0}`, label: `${name} ${minor ? 'minor' : 'major'}` })))} onChange={(value) => { const [pitch, mode] = value.split(':').map(Number); saveSong({ pitch, minor: Boolean(mode), key: `${['C', 'C♯', 'D', 'E♭', 'E', 'F', 'F♯', 'G', 'A♭', 'A', 'B♭', 'B'][pitch]} ${mode ? 'minor' : 'major'}` }) }} /></label></div><small>Analysis is an estimate. Correct BPM and key here; reload a deck to apply corrections.</small></div>}</div>
    <aside className="dj-queue" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); e.stopPropagation(); const id = e.dataTransfer.getData('application/edon-song'); if (library.songs.some((s) => s.assetId === id)) onQueue([...queue, id]); else if (e.dataTransfer.files.length) onImport(Array.from(e.dataTransfer.files)) }}><h3>Up next <span>{queue.length}</span></h3><p>Drop songs here. Auto mode follows this order.</p>{queue.map((id, index) => { const item = library.songs.find((s) => s.assetId === id); return <div className="queue-song" key={`${id}:${index}`} draggable onDragStart={(e) => e.dataTransfer.setData('application/edon-queue', String(index))} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { const from = e.dataTransfer.getData('application/edon-queue'); if (from !== '') { e.preventDefault(); e.stopPropagation(); const next = [...queue]; const [moved] = next.splice(Number(from), 1); next.splice(index, 0, moved); onQueue(next) } }}><small>{index + 1}</small><strong>{item?.name ?? 'Unavailable song'}</strong><button aria-label="Move up" onClick={() => move(index, -1)}><ArrowUp size={12} /></button><button aria-label="Move down" onClick={() => move(index, 1)}><ArrowDown size={12} /></button><button aria-label="Remove from queue" onClick={() => onQueue(queue.filter((_, i) => i !== index))}><X size={12} /></button></div> })}</aside></div>
  </section>
}
