import { useEffect, useRef, useState } from 'react'
import { Music2 } from 'lucide-react'
import { createSpotifyPlayer, playSpotifyTrack, type SpotifyPlayer } from './spotify-player'
import { SPOTIFY_CLIENT_ID, connectSpotify, disconnectSpotify, finishSpotifyLogin, searchSpotify, spotifyRedirect, spotifyTrackId, type SpotifyTrack } from './spotify'
export function SpotifyLibrary({ documentId, playing, embedOpen, onPreview, registerPause }: { documentId: string; playing: boolean; embedOpen: boolean; onPreview: () => void; registerPause: (pause: () => Promise<void>) => void }) {
  const [clientId, setClientId] = useState(() => localStorage.getItem('edon.spotify.clientId') ?? SPOTIFY_CLIENT_ID)
  const [connected, setConnected] = useState(false); const [query, setQuery] = useState(''); const [tracks, setTracks] = useState<SpotifyTrack[]>([])
  const [link, setLink] = useState(''); const [selected, setSelected] = useState<string | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const player = useRef<SpotifyPlayer | null>(null)
  const [deviceId, setDeviceId] = useState(''); const [spotifyPlaying, setSpotifyPlaying] = useState(false); const [nowPlaying, setNowPlaying] = useState({ name: '', artists: '', cover: '' })
  const sdkRequest = useRef(0)
  const pendingPlayback = useRef<Promise<void>>(Promise.resolve())
  useEffect(() => { registerPause(async () => { await pendingPlayback.current.catch(() => {}); await player.current?.pause() }) }, [registerPause])
  useEffect(() => () => { sdkRequest.current++; player.current?.disconnect() }, [])
  useEffect(() => { if (playing || !embedOpen) void player.current?.pause().catch(() => {}) }, [playing, embedOpen])
  const enablePlayer = async () => { setBusy(true); setError(''); const attempt = ++sdkRequest.current; player.current?.disconnect(); setDeviceId(''); try { const result = await createSpotifyPlayer((state) => { setSpotifyPlaying(Boolean(state && !state.paused)); setNowPlaying({ name: state?.track_window.current_track.name ?? '', artists: state?.track_window.current_track.artists.map((artist) => artist.name).join(', ') ?? '', cover: state?.track_window.current_track.album.images[0]?.url ?? '' }) }, setError); if (attempt !== sdkRequest.current) { result.player.disconnect(); return } player.current = result.player; setDeviceId(result.deviceId) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not connect Spotify player.') } finally { setBusy(false) } }
  const listen = async (id: string) => { setSelected(id); onPreview(); setError(''); if (!deviceId || !player.current) return; const active = player.current; pendingPlayback.current = (async () => { await active.activateElement(); await playSpotifyTrack(deviceId, id) })(); try { await pendingPlayback.current } catch (reason) { setError(reason instanceof Error ? reason.message : 'Spotify playback failed.') } }
  useEffect(() => { let current = true; void finishSpotifyLogin().then((ready) => { if (current) setConnected(ready) }).catch((reason: unknown) => { if (current) setError(reason instanceof Error ? reason.message : 'Login failed.') }); return () => { current = false } }, [])
  const search = async () => { setBusy(true); setError(''); try { setTracks(await searchSpotify(query)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Search failed.') } finally { setBusy(false) } }
  return <aside className="spotify-library"><header><Music2 size={17} /><strong>Spotify library</strong></header><p>Browse and listen on Spotify. Import your own audio files into decks A and B to mix.</p>{connected ? <><form onSubmit={(event) => { event.preventDefault(); void search() }}><input aria-label="Search Spotify" placeholder="Search songs or artists" value={query} onChange={(event) => setQuery(event.target.value)} /><button disabled={busy}>{busy ? 'Searching…' : query ? 'Search' : 'Liked songs'}</button></form><button onClick={() => { player.current?.disconnect(); player.current = null; sdkRequest.current++; setDeviceId(''); disconnectSpotify(); setConnected(false); setTracks([]); setSelected(null) }}>Disconnect account</button></> : <details><summary>Connect Spotify account</summary><label>Client ID<input aria-label="Spotify Client ID" value={clientId} placeholder="From your developer dashboard" onChange={(event) => setClientId(event.target.value)} /></label><small>Redirect URI: {spotifyRedirect()}</small><button onClick={() => { setError(''); void connectSpotify(clientId, documentId).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not connect.')) }}>Connect Spotify</button></details>}
  <form onSubmit={(event) => { event.preventDefault(); const id = spotifyTrackId(link); if (!id) { setError('Paste a Spotify song link, for example open.spotify.com/track/…'); return } setError(''); void listen(id) }}><label>Song link<input aria-label="Spotify song link" value={link} onChange={(event) => setLink(event.target.value)} placeholder="https://open.spotify.com/track/…" /></label><button>Listen on Spotify</button></form>{error && <p role="alert" className="music-error">{error}</p>}<div className="spotify-results">{tracks.map((track) => <button key={track.id} onClick={() => { void listen(track.id) }}>{track.album.images[0] && <img src={track.album.images[0].url} alt="" />}<span><strong>{track.name}</strong><small>{track.artists.map((artist) => artist.name).join(', ')}</small></span></button>)}</div>{connected && <div className="spotify-player-controls">{!deviceId ? <button disabled={busy} onClick={() => void enablePlayer()}>{busy ? 'Connecting…' : 'Enable Premium player'}</button> : <><div className="spotify-now-playing">{nowPlaying.cover && <img src={nowPlaying.cover} alt="Album artwork" />}<span><strong>{nowPlaying.name || 'Spotify player ready'}</strong><small>{nowPlaying.artists}</small></span></div>{selected && <a href={`https://open.spotify.com/track/${selected}`} target="_blank" rel="noreferrer">Open on Spotify</a>}<button disabled={!selected} onClick={() => { if (spotifyPlaying) void player.current?.pause(); else if (selected) void listen(selected) }}>{spotifyPlaying ? 'Pause Spotify' : 'Play selected track'}</button></>}</div>}{selected && !deviceId && embedOpen && !playing && <iframe title="Spotify song player" src={`https://open.spotify.com/embed/track/${selected}?utm_source=edon`} width="100%" height="352" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy" />}
  <small className="spotify-policy">Spotify tracks cannot be mixed, BPM-synced or equalized through its API. Spotify playback stops when you start the local mix.</small></aside>
}
